# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fitFun' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fitFun
pod 'SwiftGifOrigin'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'

end
